# Generated by Django 4.1 on 2022-09-14 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbase', '0003_remove_usuario_adm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia1', models.TextField(max_length=500)),
                ('dia2', models.TextField(max_length=500)),
                ('dia3', models.TextField(max_length=500)),
                ('dia4', models.TextField(max_length=500)),
                ('dia5', models.TextField(max_length=500)),
                ('dia6', models.TextField(max_length=500)),
                ('dia7', models.TextField(max_length=500)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
