# Generated by Django 4.1 on 2022-09-14 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0004_rutina'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='activacion',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
