# Generated by Django 4.1 on 2022-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0005_rutina_activacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='activacion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dia1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dia2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dia3',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dia4',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dia5',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dia6',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='dia7',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
