# Generated by Django 4.1 on 2022-09-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0006_alter_rutina_activacion_alter_rutina_dia1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='usuario',
        ),
    ]
