# Generated by Django 4.1 on 2022-09-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0008_rutina_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='dia1',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
