# Generated by Django 4.1 on 2022-09-16 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbase', '0009_alter_rutina_dia1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='dia1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activacion', models.TextField(blank=True, max_length=500)),
                ('dia1', models.TextField(blank=True, max_length=500)),
                ('dia2', models.TextField(blank=True, max_length=500)),
                ('dia3', models.TextField(blank=True, max_length=500)),
                ('dia4', models.TextField(blank=True, max_length=500)),
                ('dia5', models.TextField(blank=True, max_length=500)),
                ('dia6', models.TextField(blank=True, max_length=500)),
                ('dia7', models.TextField(blank=True, max_length=500)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
