# Generated by Django 4.1 on 2022-09-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0010_alter_rutina_dia1_dieta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieta',
            name='activacion',
        ),
    ]
