# Generated by Django 4.1 on 2022-09-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0013_dieta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dieta',
            old_name='usuario',
            new_name='usr',
        ),
    ]
