# Generated by Django 4.1 on 2022-09-25 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0017_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='f_pago',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
