# Generated by Django 4.1 on 2022-09-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0018_plan_f_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='doce',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ocho',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vencido',
            field=models.BooleanField(default=False),
        ),
    ]
