# Generated by Django 4.1 on 2022-09-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0019_alter_plan_doce_alter_plan_full_alter_plan_ocho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='f_pago',
            field=models.DateField(),
        ),
    ]
