# Generated by Django 4.1 on 2022-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0020_alter_plan_f_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='doce',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='full',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='ocho',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='restantes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vencido',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
