# Generated by Django 4.1 on 2022-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0023_infousr'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='InfoUsr',
        ),
    ]
