# Generated by Django 4.1 on 2022-09-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0025_alter_plan_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='restantes',
        ),
        migrations.AddField(
            model_name='plan',
            name='asistencia',
            field=models.IntegerField(default=0),
        ),
    ]
