# Generated by Django 4.1 on 2022-10-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0027_remove_plan_vencido_plan_f_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='f_pago',
            field=models.DateField(blank=True, default=False),
        ),
    ]
