# Generated by Django 4.1 on 2022-10-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0028_alter_plan_f_pago'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dieta',
            table='appbase_dieta',
        ),
    ]
