# Generated by Django 4.1 on 2022-10-13 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appbase', '0029_alter_dieta_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activacion', models.TextField(blank=True, max_length=500)),
                ('semana1', models.TextField(blank=True, max_length=500)),
                ('semana2', models.TextField(blank=True, max_length=500)),
                ('semana3', models.TextField(blank=True, max_length=500)),
                ('semana4', models.TextField(blank=True, max_length=500)),
                ('semana5', models.TextField(blank=True, max_length=500)),
                ('semana6', models.TextField(blank=True, max_length=500)),
                ('semana7', models.TextField(blank=True, max_length=500)),
                ('semana8', models.TextField(blank=True, max_length=500)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
