# Generated by Django 4.1 on 2022-10-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0031_rutinasemanal_created_rutinasemanal_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutinasemanal',
            name='f_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
