# Generated by Django 4.1 on 2022-10-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0033_rutinasemanal_cerca_cto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutinasemanal',
            old_name='cerca_cto',
            new_name='cerca_vto',
        ),
    ]
