# Generated by Django 4.1 on 2022-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0034_rename_cerca_cto_rutinasemanal_cerca_vto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinasemanal',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
