# Generated by Django 4.1 on 2022-11-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0035_alter_rutinasemanal_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='dni',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='f_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
