# Generated by Django 4.1 on 2022-11-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbase', '0036_alter_plan_dni_alter_plan_f_vencimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
